"""Public API for the Local Transcriber persistence core."""

from .config import AppConfig, RuntimePaths
from .database import SCHEMA_VERSION, Database
from .exporters import ExportFormat, TranscriptExporter, render_transcript
from .media import (
    ALLOWED_EXTENSIONS,
    DuplicateMediaError,
    InvalidMediaError,
    MediaImportError,
    MediaImportSettings,
    MediaInfo,
    MediaInspector,
    MediaLibrary,
    MediaTooLargeError,
    UnsupportedMediaError,
    sanitize_filename,
)
from .models import (
    ExportedArtifact,
    JobEvent,
    JobPhase,
    JobStatus,
    Recording,
    RecordingSearchResult,
    Segment,
    Subject,
    Transcript,
    TranscriptionJob,
    TranscriptionMetrics,
    TranscriptionSettings,
    Word,
)
from .models_manager import (
    SUPPORTED_MODELS,
    ModelDownloadConfirmationError,
    ModelError,
    ModelManager,
    ModelNotInstalledError,
    ModelStatus,
)
from .queueing import TranscriptionQueue, TranscriptionWorker
from .repository import Repository
from .transcription import (
    CTranslate2RuntimeProbe,
    EngineOutput,
    FasterWhisperEngine,
    ProfileResolver,
    ProgressEvent,
    ResolvedProfile,
    RuntimeCapabilities,
    RuntimeProfileError,
    TranscriptionCancelled,
    TranscriptionEngine,
    TranscriptionRequest,
    TranscriptionService,
)

__all__ = [
    "AppConfig",
    "ALLOWED_EXTENSIONS",
    "Database",
    "DuplicateMediaError",
    "ExportFormat",
    "ExportedArtifact",
    "InvalidMediaError",
    "JobEvent",
    "JobPhase",
    "JobStatus",
    "MediaImportError",
    "MediaImportSettings",
    "MediaInfo",
    "MediaInspector",
    "MediaLibrary",
    "MediaTooLargeError",
    "ModelDownloadConfirmationError",
    "ModelError",
    "ModelManager",
    "ModelNotInstalledError",
    "ModelStatus",
    "Recording",
    "RecordingSearchResult",
    "Repository",
    "RuntimePaths",
    "SCHEMA_VERSION",
    "SUPPORTED_MODELS",
    "Segment",
    "Subject",
    "Transcript",
    "TranscriptExporter",
    "TranscriptionJob",
    "TranscriptionMetrics",
    "TranscriptionEngine",
    "TranscriptionCancelled",
    "TranscriptionQueue",
    "TranscriptionRequest",
    "TranscriptionService",
    "TranscriptionSettings",
    "TranscriptionWorker",
    "UnsupportedMediaError",
    "Word",
    "CTranslate2RuntimeProbe",
    "EngineOutput",
    "FasterWhisperEngine",
    "ProfileResolver",
    "ProgressEvent",
    "ResolvedProfile",
    "RuntimeCapabilities",
    "RuntimeProfileError",
    "render_transcript",
    "sanitize_filename",
]
